export const heroMap: Record<string, string> = {
  "Captain America": "캡틴 아메리카",
  "Iron Man": "아이언맨",
  "Spider-Man": "스파이더맨",
  Hulk: "헐크",
  "Black Widow": "블랙위도우",
  Hawkeye: "호크아이",
  "Black Panther": "블랙팬서",
  "Doctor Strange": "닥터 스트레인지",
  "Scarlet Witch": "스칼렛 위치",
  "Winter Soldier": "윈터 솔저",
  "Star-Lord": "스타로드",
  Mantis: "맨티스",
  "Adam Warlock": "아담 워록",
  Magneto: "매그니토",
  Wolverine: "울버린",
  Phoenix: "피닉스",
  Storm: "스톰",
  "Luna Snow": "루나 스노우",
  "Rocket Raccoon": "로켓 라쿤",
  Groot: "그루트",
  Loki: "로키",
  Hela: "헬라",
  Namor: "네이머",
  "Peni Parker": "페니 파커",
  Punisher: "퍼니셔",
  "Squirrel Girl": "스쿼럴 걸",
  Thor: "토르",
  "The Thing": "더 씽",
  "Human Torch": "휴먼 토치",
  "Mister Fantastic": "미스터 판타스틱",
  "Invisible Woman": "인비저블 우먼",
  "Moon Knight": "문 나이트",
  Psylocke: "사일록",
  "Emma Frost": "엠마 프로스트",
  "Elsa Bloodstone": "엘사 블러드스톤",
  Magik: "매직",
  "Cloak & Dagger": "클록 & 대거",
  Cloak: "클록",
  Dagger: "대거",
  Deadpool: "데드풀",
  "Black Cat": "블랙 캣",
  "Iron Fist": "아이언 피스트",
  "White Fox": "화이트 폭스",
  Blade: "블레이드",
  Venom: "베놈",
  Ultron: "울트론",
  "Monster Hulk": "몬스터 헐크",
  "Jeff the Land Shark": "제프 더 랜드 샤크",
};
