export const skillMap: Record<string, string> = {
  // 캡틴 아메리카
  "Sentinel Strike": "방패 강타(좌클릭)",
  "Super-Soldier Slam": "든든한 지원(좌클릭)",
  "Living Legend": "절대 의지(우클릭)",
  "Leading Dash": "진두 지휘(Shift)",
  "Vibranium Energy Saw": "비브라늄 에너지 방패(E)",
  "Liberty Rush": "파죽지세(F)",
  "Freedom Charge": "자유의 부름(Q)",
  "Captain's Spirit": "불굴의 캡틴(C)",
  "Charged Aegis": "초전도 방패(C)",

  // 아이언맨
  "Repulsor Blast": "리펄서 블래스트(좌클릭)",
  Unibeam: "유니 빔(우클릭)",
  "Hyper-Velocity": "고속 부스터(Shift)",
  "Armor Overdrive": "아머 오버드라이브(E)",
  "Micro-Missile Barrage": "미사일 폭격(F)",
  "Invincible Pulse Cannon": "무적 펄스 캐논(Q)",
  "Nano Tech": "나노 기술(패시브)",
  "Gamma Overdrive": "감마 오버드라이브(E)",

  // 토르
  Thorforce: "토르의 힘(패시브)",
  "Mjolnir Bash": "묠니르 강격(좌클릭)",
  "Hammer Throw": "해머 투척(우클릭)",
  "Storm Surge": "라이트닝 스톰(Shift)",
  "Lightning Realm": "천둥의 영역(E)",
  "Awakening Rune": "룬의 각성(F)",
  "God of Thunder": "천둥의 신(Q)",
  "Odinson Reborn": "토르 부활(패시브)",
  "Thunderous Deity": "신의 가호(패시브)",

  // 라쿤
  "Wild Crawl": "최전선 걷기(패시브)",
  "Flying Ace": "에이스 파일럿(패시브)",
  "Bombard Mode": "화력 폭격(좌클릭)",
  "Repair Mode": "치유의 라이트 볼(우클릭)",
  "Jetpack Dash": "로켓 대시(Shift)",
  "B.R.B.": "부활 비콘(E)",
  "C.Y.A.": "코스믹 에너지 증폭 체인(Q)",
  "Old Friends": "오래된 사이(C)",
  "Web Server": "웹 서버(E)",
  "Ammo Invention": "무기상(Z)",

  // 루나 스노우
  "Smooth Skate": "아이스 셰이드(패시브)",
  "Cryo Heart": "얼어붙은 심장(패시브)",
  "Light & Dark Ice": "빛과 어둠의 교차(좌클릭)",
  "Absolute Zero": "절대 영도(우클릭)",
  "Ice Arts": "눈의 춤(Shift)",
  "Share The Stage": "아이돌의 매력(E)",
  "Fate of Both Worlds": "운명 교향곡(Q)",
  "Lunar Chi": "다시 찾은 고향의 냉기(패시브)",
  "Light & Shadow Karma": "빛과 그림자의 카르마(C)",
  "Icy Disco": "눈의 노래(패시브)",
  "Frozen Chi": "서늘한 남풍(C)",

  // 그루트
  "Flora Colossus": "플로라 콜로서스(패시브)",
  "Vine Strike": "가시 덩굴(좌클릭)",
  "Spore Bomb": "포자 폭탄(우클릭)",
  "Thornlash Wall": "가시 장벽(Shift)",
  "Ironwood Wall": "쇠나무 장벽(E)",
  "Furious Flora": "분노한 플로라(기타)",
  "Strangling Prison": "절대 속박(Q)",
  "Friendly Shoulder": "든든한 아군(패시브)",
  "Wild Wall": "야생 장벽(C)",

  //헐크
  "Gamma Ray Gun": "감마 레이건(좌클릭)",
  "Gamma Grenade": "감마 폭탄(Shift)",
  "Puny Banner": "약골 배너(Q)",
  "Heavy Blow": "스매시(좌클릭)",
  "Gamma Burst": "감마 버스트(우클릭)",
  "Indestructible Guard": "견고한 가드(Shift)",
  "Radioactive Lockdown": "방사선 감옥(E)",
  "Incredible Leap": "인크레더블 점프(기타)",
  "Hulk Smash!": "헐크 스매시!(Q)",
  "World Breaker": "지구 파괴자(Q)",
  "Gamma Boost": "감마 부스터(패시브)",
  "Gamma Fastball": "감마 볼(C)",

  // 블랙위도우
  "Widow's Bite Baton": "위도우 바이트(좌클릭)",
  "Red Room Rifle": "레드룸 라이플(좌클릭)",
  "Straight Shooter": "크리티컬 샷(우클릭)",
  "Fleet Foot": "날렵한 발걸음(Shift)",
  "Edge Dancer": "에이전트 마스터리(E)",
  "Electro-Plasma Explosion": "에너지 버스트(Q)",
  "Pulse Rifle": "펄스 라이플(C)",
  "Supersensory Hunt": "초감각 추적(C)",

  // 호크아이
  "Archer'S Focus": "매의 시야(패시브)",
  "Piercing Arrow": "피어싱 애로우(좌클릭)",
  "Blast Arrow": "블라스트 애로우(좌클릭)",
  "Crescent Slash": "반달 베기(Shift)",
  "Hypersonic Arrow": "하이퍼소닉 애로우(E)",
  "Ronin Slash": "허공베기(기타)",
  "Skyward Leap": "비상하는 매(기타)",
  "Hunter's Sight": "매의 시선(Q)",
  "Ice Arrow": "얼음 화살(C)",
  "Supersensory Vision": "초감각 시야(패시브)",

  // 블랙 팬서
  "Panther's Cunning": "블랙 팬서 아머(패시브)",
  "Vibranium Claws": "비브라늄 클로(좌클릭)",
  "Spear Toss": "투창(우클릭)",
  "Spirit Rend": "유성 충돌(Shift)",
  "Spinning Kick": "회전 킥(E)",
  "Subtle Step": "그림자 밟기(기타)",
  "Bast's Descent": "바스테드 강림(Q)",
  "Wakandan Master": "와칸다 히치하이크(C)",

  // 닥터스트레인지
  "Price of Magic": "마법의 대가(패시브)",
  "Daggers of Denak": "데낙의 단검(좌클릭)",
  "Shield of the Seraphim": "세라핌 실드(우클릭)",
  "Cloak of Levitation": "공중부양 망토(Shift)",
  "Maelstrom of Madness": "암흑의 소용돌이(E)",
  "Pentagram of Farallah": "파랄라의 오성진(F)",
  "Eye of Agamotto": "아가모토의 눈(Q)",
  "Enchanted Enhancement": "마력 강화(패시브)",
  "Gamma Maelstrom": "감마 소용돌이(E)",

  // 스칼렛위치
  "Chaos Control": "카오스 컨트롤(좌클릭)",
  "Chthonian Burst": "카오스 블라스트(우클릭)",
  "Mystic Projection": "미스틱 프로젝션(Shift)",
  "Dark Seal": "암흑의 봉인(E)",
  Telekinesis: "염동력(기타)",
  "Reality Erasure": "현실 삭제(Q)",
  "Sorcery Surge": "마력 폭주(C)",
  "Chaotic Bond": "혼돈의 인연(패시브)",

  // 윈터솔져
  "Ceaseless Charge": "끝없는 화력(패시브)",
  Roterstern: "재의 심판(좌클릭)",
  "Bionic Hook": "데스 로프(우클릭)",
  "Trooper's Fist": "스컬 크러시(Shift)",
  "Tainted Voltage": "초강력 전류(E)",
  "Kraken Impact": "인크레더블(Q)",
  "Stellar Impact": "스텔라 임팩트(C)",
  "Infinite Grit": "인피니트 솔져(패시브)",

  // 스타로드
  "Element Guns": "쿼드 블래스터(좌클릭)",
  "Stellar Shift": "스텔라 시프트(우클릭)",
  "Rocket Propulsion": "로켓 부스터(Shift)",
  "Blaster Barrage": "블래스터 폭격(E)",
  "Galactic Legend": "레전드 등장(Q)",
  "Astral Jump": "네트워크 리프스파이더(C)",
  "Leader's Soul": "개척의 영혼(패시브)",

  // 맨티스
  "Nature's Favor": "자연의 가호(패시브)",
  "Life Energy Blast": "꺼져가는 생명(좌클릭)",
  "Healing Flower": "치유의 꽃(우클릭)",
  "Spore Slumber": "수면 포자(Shift)",
  "Allied Inspiration": "격려(E)",
  "Natural Anger": "자연의 분노(F)",
  "Soul Resurgence": "영혼의 공명(Q)",
  "Heavenly Guardian": "천상의 수호자(패시브)",
  "Nature's Soul": "자연의 영혼(패시브)",

  // 아담워록
  "Regenerative Cocoon": "부활 고치(패시브)",
  "Quantum Magic": "양자 마법(좌클릭)",
  "Cosmic Cluster": "코즈믹 클러스터(우클릭)",
  "Soul Bond": "영혼의 공명(Shift)",
  "Avatar Life Stream": "생명의 흐름(E)",
  "Karmic Revival": "텔레키네시스 부활(Q)",
  "Cosmic Awareness": "코스믹 어웨어니스(패시브)",
  "Soul Perseverance": "얼어붙은 영혼(패시브)",

  // 매그니토
  "Magnetic Descent": "자기장 하강(패시브)",
  "Iron Volley": "자기력 볼(좌클릭)",
  "Mag-Cannon": "자기장 캐논(우클릭)",
  "Metallic Curtain": "아이언 배리어(Shift)",
  "Metal Bulwark": "아이언 실드(E)",
  "Iron Bulwark": "자기력 실드(F)",
  "Meteor M": "메테오 스톰(Q)",
  "Magnetic Resonance": "마그네틱 공명(C)",
  "Metallic Fusion": "금속 융합(C)",

  // 울버린
  "Regenerative Healing Factor": "재생 치유 세포(패시브)",
  "Berserker Rage": "버서커의 분노(패시브)",
  "Savage Claw": "강철 발톱(좌클릭)",
  "Vicious Rampage": "블러디 어택(우클릭)",
  "Feral Leap": "맹수의 습격(Shift)",
  "Undying Animal": "최후의 발악(E)",
  "Last Stand": "결사의 전투(Q)",
  "Metal Cannonball": "속구 어택(C)",
  "Phoenix Warrior": "피닉스 전사(Shift)",

  // 피닉스
  "Cosmic Flame": "코스믹 플레임(좌클릭)",
  "Telekinesis Burst": "텔레키네시스 폭발(우클릭)",
  "Telepathic Illusion": "텔레파시 환영(Shift)",
  "Dark Ascent": "어두운 상승(E)",
  "Endsong Inferno": "엔드송 인페르노(Q)",
  "Mind's Grace": "생각의 은총(패시브)",

  // 스톰
  "Wind Blade": "윈드 블레이드(좌클릭)",
  "Bolt Rush": "전류(우클릭)",
  "Weather Control": "날씨 조종(Shift)",
  "Goddess Boost": "여신의 손길(E)",
  "Omega Hurricane": "오메가 스톰(Q)",
  "Shark Surge": "상어 스톰(패시브)",
  "Charged Gale": "차징 질풍(C)",
  "Burning Hurricane": "화염 허리케인(X)",

  // 사일록
  "Psionic Crossbow": "화살·진정한 비상(좌클릭)",
  "Wing Shurikens": "별·귀환하는 날개(우클릭)",
  "Psi-Blade Dash": "인법·꽃을 가르는 칼날(Shift)",
  "Psychic Stealth": "회피·신의 안개(E)",
  "Dance of the Butterfly": "오의·나비 그림자의 난무(Q)",
  "Psychic Echoes": "사이킥 에코(C)",
  "Psionic Disc": "사이오닉 디스크(C)",

  // 엠마
  "Telepathic Pulse": "텔레파시 충격(좌클릭)",
  "Mind's Aegis": "마인드 실드(우클릭)",
  "Diamond Form": "다이아몬드 형태(Shift)",
  "Faceted Fury": "크리스탈 퓨리(좌클릭)",
  "Crystal Kick": "크리스탈 킥(우클릭)",
  "Carbon Crush": "다이아 크러시(E)",
  "Psychic Spear": "사이킥 스피어(E)",
  "Psionic Seduction": "텔레파시 컨트롤(Q)",
  "Mind Link": "정신 연결(패시브)",

  // 매직
  "Limbo's Might": "마법 갑옷(패시브)",
  Soulsword: "소울 소드(좌클릭)",
  "Magik Slash": "매직 슬래쉬(우클릭)",
  "Stepping Discs": "지옥의 발걸음(Shift)",
  "Eldritch Whirl": "영혼의 소용돌이(좌클릭)",
  "Demon's Rage": "악마의 불꽃(우클릭)",
  "Umbral Incursion": "어둠의 습격(E)",
  Darkchild: "다크 차일드(Q)",
  "Disc Master": "변경의 히치하이크(패시브)",

  // 네이머
  "Trident of Neptune": "넵튠의 트라이던트(좌클릭)",
  "Wrath of the Seven Seas": "일곱 바다의 죄악(우클릭)",
  "Blessing of the Deep": "심해의 가호(Shift)",
  "Aquatic Dominion": "탈로칸의 통제(E)",
  "Tide Fall": "윈드 웨이브(기타)",
  "Horn of Proteus": "웨일 웨이브(Q)",
  "Gamma Monstro": "감마 몬스터(C)",
  "Frozen Spawn": "얼어붙은 알(C)",

  // 미스터판타스틱
  "Elastic Strength": "무한 왕복(패시브)",
  "Stretch Punch": "탄력 펀치(좌클릭)",
  "Distended Grip": "탄력 속박(우클릭)",
  "Reflexive Rubber": "방탄 고무(Shift)",
  "Flexible Elongation": "유연성(E)",
  "Brainiac Bounce": "쾌속 바운드(Q)",
  "Wedded Harmony": "은하를 찌를 듯한 조화(C)",

  // 인비
  "Convert Advance": "은밀 전진(패시브)",
  "Orb Projection": "오브 프로젝션(좌클릭)",
  "Guardian Shield": "가디언 실드(우클릭)",
  "Psionic Vortex": "사이오닉 소용돌이(Shift)",
  "Force Physics": "포스 피직스(E)",
  "Agile Strike": "민첩 타격(기타)",
  "Veiled Step": "베일 스텝(기타)",
  "Invisible Boundary": "투명 경계(Q)",
  "Fantasti-Force": "환상적인 힘(패시브)",
};
