export const systemGlossary: Record<string, string> = {
  "Greetings, Rivals!": "라이벌 여러분, 안녕하세요!",
  "We're thrilled to announce the upcoming patch drops on": "다가오는 패치가 적용되는 시간을 안내드립니다:",
  "No server downtime; just patch and play!": "서버 점검 없이 패치 후 바로 플레이할 수 있습니다!",
  "Here's what's coming your way:": "이번 업데이트 내용은 다음과 같습니다:",
  "More surprises and changes are coming soon! See you in the next update!": "더 많은 놀라움과 변경 사항이 곧 찾아옵니다! 다음 업데이트에서 만나요!",
  "All Platforms": "전체 플랫폼",
  "All-New Content": "신규 콘텐츠",
  "All-New Mode": "신규 모드",
  "Cinematic Crossover": "시네마틱 크로스오버",
  "Bug Fixes": "버그 수정",
  "Chain-CC Protection": "연속 CC 보호",
  Console: "콘솔",
  Consoles: "콘솔",
  Event: "이벤트",
  "Fixes and Optimizations": "수정 및 최적화",
  Heroes: "히어로",
  "Known Issues": "알려진 문제",
  Maintenance: "점검",
  "New In Store": "상점 추가 상품",
  "New Event": "신규 이벤트",
  "New Hero": "신규 영웅",
  "New": "새로운",
  "Lore": "세계관",
  "Clear Eyes, Full Hearts": "맑은 눈, 가득한 마음",
  "Clearing the Path": "길을 비키우는",
  "One Last Shot": "마지막 한 발",
  "Patch Size": "패치 용량",
  Platform: "플랫폼",
  Platforms: "플랫폼",
  "Server Maintenance": "서버 점검",
  "Team Lobby": "팀 로비",
  Tenacity: "강인함",
  "Tournament": "토너먼트",
  "Series": "시리즈",
  "Ultimate Ability VFX": "궁극기 이펙트",
  "Ultimate Ability": "궁극기",
  "Available From": "판매 시작",
  "Limited Time": "기간 한정",
  "Event Period": "이벤트 기간",
  "Event Duration": "이벤트 기간",
  "Daily Showtimes": "일일 상영 시간",
  "Drops Period": "드롭스 기간",
  "Battle Pass": "배틀 패스",
  "Customizable Components": "커스터마이즈 구성요소",
  Chroma: "크로마",
  Costume: "코스튬",
  Costumes: "코스튬",
  Emoji: "이모지",
  Spray: "스프레이",
  Nameplate: "네임플레이트",
  "Marvel Studios’ The Avengers": "마블 스튜디오 어벤져스",
  "The Avengers": "어벤져스",
  "Marvel Rivals": "마블 라이벌즈",
  "Blood Hunt": "블러드 헌트",
  "Hellfire Gala": "헬파이어 갈라",
  "Dev Vision": "개발자 비전",
  "Will of Galacta": "갈락타의 의지",
  "Suave Spector": "수려한 스펙터",
  "Primal Groove": "원시 그루브",
  "Soulless Sword": "소울리스 소드",
  "Weapon M": "웨폰 M",
  "White Crown": "화이트 크라운",
  "Shadowed Gaze": "셰도우드 게이즈",
  "Green Glow": "그린 글로우",
  "Neon Nemesis": "네온 네메시스",
  // Elsa Bloodstone
  "MONSTER-PIERCER": "몬스터 피어서",
  "INHERITED INSTINCT": "유전된 본능",
  "RUTHLESS PURSUIT": "무자비한 추격",
  "HELIX ADVANCE": "헬릭스 전진",
  "LIVING BULLET": "리빙 불릿",
  "SMOKY SNARE": "스모키 올가미",
  "BLOODSTONE'S BOOMBOX BULLETS": "블러드스톤의 붐박스 불릿",
  "APEX PREDATOR": "최상위 포식자",
  // Devil Dinosaur
  "Primal Bite": "원시 물기",
  "Impact Beam": "충격 빔",
  "Buddy Barrier": "버디 배리어",
  "Savage Predation": "야만적 포식",
  "Frenzied Feast": "광란의 연회",
  Increase: "증가",
  Reduce: "감소",
  Bundle: "번들",
  Emote: "감정표현",
  Accessory: "액세서리",
  PC: "PC",
  PvE: "PvE",
  Twitch: "트위치",
  "Beach Bod": "비치 보디",
  "Fantastic": "판타스틱",
  "X-Press": "X-프레스",
  Juice: "쥬스",
  Rivals: "라이벌즈",
  // Season 8.5 summer bundles
  "Breezy Butterfly": "브리즈 버터플라이",
  "Robe of Relaxation": "로브 오브 릴렉세이션",
  "Azure Shade": "애저 셰이드",
  "Aqua Arsenal": "아쿠아 아스날",
  "Polarity Bond": "폴라리티 본드",
  "Polarity Soldier": "폴라리티 솔저",
};
