export const systemGlossary: Record<string, string> = {
  "All Platforms": "전체 플랫폼",
  "All-New Content": "신규 콘텐츠",
  "All-New Mode": "신규 모드",
  "Cinematic Crossover": "시네마틱 크로스오버",
  "Bug Fixes": "버그 수정",
  "Chain-CC Protection": "연속 CC 보호",
  Console: "콘솔",
  Consoles: "콘솔",
  Event: "이벤트",
  "Fixes and Optimizations": "수정 및 최적화",
  Heroes: "히어로",
  "Known Issues": "알려진 문제",
  Maintenance: "점검",
  "New In Store": "상점 추가 상품",
  "Patch Size": "패치 용량",
  Platform: "플랫폼",
  Platforms: "플랫폼",
  "Server Maintenance": "서버 점검",
  "Team Lobby": "팀 로비",
  Tenacity: "강인함",
  "Ultimate Ability VFX": "궁극기 이펙트",
  "Ultimate Ability": "궁극기",
  "Available From": "판매 시작",
  "Limited Time": "기간 한정",
  "Event Period": "이벤트 기간",
  "Event Duration": "이벤트 기간",
  "Daily Showtimes": "일일 상영 시간",
  "Drops Period": "드롭스 기간",
  "Battle Pass": "배틀 패스",
  "Customizable Components": "커스터마이즈 구성요소",
  "Marvel Studios’ The Avengers": "마블 스튜디오 어벤져스",
  "The Avengers": "어벤져스",
  "Marvel Rivals": "마블 라이벌즈",
  "Blood Hunt": "블러드 헌트",
  "Hellfire Gala": "헬파이어 갈라",
  "Dev Vision": "개발자 비전",
  "Will of Galacta": "갈락타의 의지",
  Increase: "증가",
  Reduce: "감소",
  Bundle: "번들",
  Emote: "감정표현",
  Accessory: "액세서리",
  PC: "PC",
  PvE: "PvE",
  Twitch: "트위치",
};
